version: "3.6"

services:

  elasticsearch:
    build:
      context: elasticsearch/
    image: elasticsearch-${ELASTICSEARCH_VERSION:-6.3.1}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      LOGSPOUT: ignore
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"

  logstash:
    build:
      context: logstash/
    image: logstash-${LOGSTASH_VERSION:-6.3.1}
    ports:
      - "${LOGSTASH_TCP_PORT:-5000}:${LOGSTASH_TCP_PORT:-5000}/tcp"
      - "${LOGSTASH_UDP_PORT:-5000}:${LOGSTASH_UDP_PORT:-5000}/udp"
    environment:
      TCP_PORT: ${LOGSTASH_TCP_PORT:-5000}
      UDP_PORT: ${LOGSTASH_UDP_PORT:-5000}
      LOGSPOUT: ignore
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"

  kibana: 
    build:
      context: kibana/
    image: kibana-${KIBANA_VERSION:-6.3.1}
    environment:
      LOGSPOUT: ignore