version: "3.6"

services:

  filebeat:
    build:
      context: beats/filebeat
    image: filebeat-${FILEBEAT_VERSION:-6.3.1}
    user: root
    networks:
      - filebeat
    # disable strict permission checks
    command: ["--strict.perms=false"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - INDEX_NAME=${FILEBEAT_INDEX_NAME:-filebeat}