version: '3'

services:
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://${LOGSTASH_URL}
      LOGSTASH_TAGS: ${LOGSTASH_TAGS}
    restart: always