# https://github.com/elastic/elasticsearch-docker
ARG ELASTICSEARCH_IMAGE_URL=docker.elastic.co/elasticsearch/elasticsearch
ARG ELASTICSEARCH_VERSION=6.3.1
FROM ${ELASTICSEARCH_IMAGE_URL}:${ELASTICSEARCH_VERSION}