version: "3.7"

services:

  curator:
    build:
      context: ../images/curator/
    image: curator-${CURATOR_VERSION:-5.5.4}
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - CURATOR_INDEX_PATTERN=${CURATOR_INDEX_PREFIX:-filebeat-}
    restart: on-failure