version: "3.7"
services:

  elasticsearch:
    build:
      context: ../images/elasticsearch/
      args:
        ELASTICSEARCH_IMAGE_URL: ${ELASTICSEARCH_IMAGE_URL:-elasticsearch}
        ELASTICSEARCH_VERSION: ${ELASTICSEARCH_VERSION:-7.1.0}
    image: elasticsearch-${ELASTICSEARCH_VERSION:-7.1.0}
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    environment:
      LOGSPOUT: ignore
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      node.name: elasticsearch_1
      cluster.name: docker-cluster
      cluster.initial_master_nodes: elasticsearch_1
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${ELASTICSEARCH_DATA:-/elk/elasticsearch}:/usr/share/elasticsearch/data:rw
      - $PWD/images/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      elk:
        aliases:
          - elasticsearch
    restart: on-failure

  logstash:
    build:
      context: ../images/logstash/
      args:
        LOGSTASH_IMAGE_URL: ${LOGSTASH_IMAGE_URL:-logstash}
        LOGSTASH_VERSION: ${LOGSTASH_VERSION:-7.1.0}
    image: logstash-${LOGSTASH_VERSION:-7.1.0}
    ports:
      - "${LOGSTASH_TCP_PORT:-5000}:${LOGSTASH_TCP_PORT:-5000}/tcp"
      - "${LOGSTASH_UDP_PORT:-5000}:${LOGSTASH_UDP_PORT:-5000}/udp"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      TCP_PORT: ${LOGSTASH_TCP_PORT:-5000}
      UDP_PORT: ${LOGSTASH_UDP_PORT:-5000}
      LOGSPOUT: ignore
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    volumes:
      - $PWD/images/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - $PWD/images/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      elk:
        aliases:
          - logstash
    depends_on:
      - elasticsearch
    restart: on-failure

  kibana: 
    build:
      context: ../images/kibana/
      args:
        KIBANA_IMAGE_URL: ${KIBANA_IMAGE_URL:-kibana}
        KIBANA_VERSION: ${KIBANA_VERSION:-7.1.0}
    image: kibana-${KIBANA_VERSION:-7.1.0}
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
#      KIBANA_BASE_PATH: ${KIBANA_BASE_PATH:-/}
      LOGSPOUT: ignore
    ports:
      - "5601:5601"
    volumes:
      - ${KIBANA_DATA:-/elk/kibana}:/usr/share/kibana/data:rw
      - $PWD/images/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      elk:
        aliases:
          - kibana
    depends_on:
      - elasticsearch
    restart: on-failure

networks:
  elk:
    driver: bridge