version: "3.6"

services:

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    hostname: swarm-listener
    networks:
      - elk
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: dockerflow/docker-flow-proxy:latest
    hostname: proxy
    ports:
      - "80:80"
      - "443:443"
      - "9200:9200"
      - "5601:5601"
    networks:
      - elk
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=9200,5601

  elasticsearch:
    hostname: "{{.Node.Hostname}}-elasticsearch"
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - node.name={{.Node.Hostname}}-elasticsearch     
    networks:
      - elk
    deploy:
      mode: 'global'
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    hostname: "{{.Node.Hostname}}-logstash"
    networks:
      - elk
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf

  kibana:
    hostname: "{{.Node.Hostname}}-kibana"
    environment:
      - SERVER_NAME="{{.Node.Hostname}}-kibana"
    networks:
      - elk
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=5601
        - com.df.srcPort=5601
    volumes:
      - kibana:/usr/share/kibana/data
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/logstash.yml

networks:
  elk:
    external: true

volumes:
  elasticsearch:
  kibana:

configs:
  elasticsearch_config:
    file: $PWD/images/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: $PWD/images/logstash/config/logstash.yml
  logstash_pipline:
    file: $PWD/images/logstash/pipeline/logstash.conf
  kibana_config:
    file: $PWD/images/kibana/config/kibina.yml