version: "3.6"
services:

  heartbeat:
    user: root
    build:
      context: ../images/beats/heartbeat
    image: heartbeat-${HEARTBEAT_VERSION:-6.6.1}
    # disable strict permission checks
    command: ["--strict.perms=false"]
    restart: on-failure
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}
      INDEX_NAME: ${HEARTBEAT_INDEX_NAME:-heartbeat}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-http://elasticsearch:9200}
      KIBANA_HOST: ${KIBANA_HOST:-http://kibana:5601}
    volumes:
      - ${HEARTBEAT_DATA:-/elk/heartbeat}:/usr/share/heartbeat/data:rw
      - $PWD/beats/heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    networks:
      - heartbeat

networks:
  heartbeat:
    driver: bridge